In [47]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import cv2
from PIL import Image
import glob
import os
import pandas as pd 
import random

## class for records image name

In [50]:
class MyImage:
    def __init__(self, img_name):
        self.img = cv2.imread(img_name)
        self.__name = img_name

    def __str__(self):
        return self.__name

In [108]:
df_label = pd.read_csv("trainLabels.csv")
df_label.head()

image  level
0   10_left      0
1  10_right      0
2   13_left      0
3  13_right      0
4   15_left      1

## pre-train process

In [130]:
im = []
im_name = []
for img in glob.glob("data/processed/512/*.jpeg"):

    image=cv2.imread(img,0)
    ravel = image.ravel() #2d -> 1d
    im.append(ravel)
    im_name.append(str(img))


In [131]:
im_name[:10]

['data/processed/512/16591_right$processed512.jpeg',
 'data/processed/512/13667_right$processed512.jpeg',
 'data/processed/512/1353_left$processed512.jpeg',
 'data/processed/512/18274_left$processed512.jpeg',
 'data/processed/512/18307_left$processed512.jpeg',
 'data/processed/512/17202_left$processed512.jpeg',
 'data/processed/512/18092_left$processed512.jpeg',
 'data/processed/512/13517_right$processed512.jpeg',
 'data/processed/512/12305_right$processed512.jpeg',
 'data/processed/512/19405_right$processed512.jpeg']

In [132]:
im[:10]

[array([79, 79, 77, ..., 85, 85, 85], dtype=uint8),
 array([135, 134, 133, ..., 111, 112, 112], dtype=uint8),
 array([113, 110, 110, ...,  68,  68,  69], dtype=uint8),
 array([136, 133, 131, ..., 105, 100,  96], dtype=uint8),
 array([123, 124, 124, ...,  67,  66,  63], dtype=uint8),
 array([121, 122, 123, ..., 110, 111, 111], dtype=uint8),
 array([55, 54, 54, ..., 54, 53, 53], dtype=uint8),
 array([167, 169, 171, ..., 169, 164, 164], dtype=uint8),
 array([ 86,  86,  87, ..., 103, 104, 106], dtype=uint8),
 array([113, 114, 115, ..., 139, 140, 140], dtype=uint8)]

In [133]:
start_time = time.time()

df_im = pd.DataFrame(im) 
df_im.to_csv('data/mlinput/image512.csv')
df_im.head()

print("--- %s seconds ---" % (time.time() - start_time))

--- 9965.3774228096 seconds ---


# processing train labels and merge with image dataset

In [134]:
df_name = pd.DataFrame(im_name)  
im_name = df_name[0].str.split('$', expand = True)
im_name = im_name[0].str.split('/', expand = True)
im_name = im_name.rename(index=str, columns={3: "image"})

im_name.head()

0          1    2        image
0  data  processed  512  16591_right
1  data  processed  512  13667_right
2  data  processed  512    1353_left
3  data  processed  512   18274_left
4  data  processed  512   18307_left

In [135]:
start_time = time.time()
df_merge = pd.merge(im_name, df_label, how = 'left', on = 'image')
df_label_new = df_merge[["image",'level']]
df_label_new.to_csv('data/mlinput/label512.csv')
df_label_new.head()

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.3862009048461914 seconds ---


In [19]:
label = pd.read_csv('trainLabels.csv', encoding="ISO-8859-1")
label.head()

image  level
0   10_left      0
1  10_right      0
2   13_left      0
3  13_right      0
4   15_left      1